services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
  frontend:
    build: ./client
    container_name: frontend
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend


