services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    container_name: frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    



