services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://16.16.207.59:3000/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend


